baseURL = "https://AshrafulIslamDE.github.io/my_thoughts/"
languageCode = "en-us"
title = "My Thoughts"
theme = "PaperMod"
[pagination]
  pagerSize = 5

[params]
  author = "Md Ashraful Islam"
  description = "Data Scientist | AI & ML Engineer | Python | PyTorch | LLM | RAG"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/AshrafulIslamDE"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/md-ashraful-islam-de"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:md.ashraful.islam.de@gmail.com"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30
